### ISSUE TITLE
Cors origin issue while trying to send an event from flutter web side.

### ISSUE THREAD

**Issue by ahmedGibran** [bostrot/flutter_plausible_analytics#3]
**Describe the bug**
We using event function to set a new event but  we facing cors origin error , any suggestions here? 
![Screenshot 2022-09-05 at 16 26 54](https://user-images.githubusercontent.com/51888694/188481225-81ad62af-6e90-4138-a521-07bbbd776503.png)
![Screenshot 2022-09-05 at 17 25 50](https://user-images.githubusercontent.com/51888694/188481330-6e5fe521-a579-438e-88b6-053402912d76.png)

**Comment by bostrot** [comment]
It seems like CORS has to be enabled/allowed on your server. The process is different depending on what system you use.
Are you using a reverse proxy in front of your Plausible instance?
