### ISSUE TITLE
Shouldn't X-Forwarder-For be left?

### ISSUE THREAD

**Issue by TheLastGimbus** [bostrot/flutter_plausible_analytics#4]
hi!

i'm looking into implementation of this:

https://github.com/bostrot/flutter_plausible_analytics/blob/1d8a0d88caf0c87f7db74cc8de55a8e79c1d9cb3/lib/plausible_analytics.dart#L52

Shouldn't this be left? How is plausible supposed to generate unique ids now?

Also, i've been thinking of a way of getting actual user ids - generating random uuid at the first app start, and then using that - but seems that plausible wants to be so private that this isn't much supported: https://github.com/plausible/analytics/discussions/1141#discussioncomment-903043

On the other hand, this way we're going to get much more unique users than there actually are :thinking:

**Comment by bostrot** [comment]
With "left" you mean not sending it with the request? (according to plausible docs it is required to have it: https://plausible.io/docs/events-api#request-headers)

Although I agree that the current config probably won't count every single visitor. Correct me if I am wrong but sending another request to get the users IP first is not ideal. (any ideas?) 

Also generating the IDs might be an option but I guess that would go against the whole point of Plausible being GDPR compliant and you would (at least in the EU) need to ask the users first :(

EDIT:
Also Plausible generates the user id from the following:
daily_salt + website_domain + ip_address + user_agent

So when user agent includes as much details as possible it might be more accurate.

**Comment by TheLastGimbus** [comment]
`X-Forwarded-For` is header used by reverse-proxies (web servers that manage your SSL, protocols etc) like nginx or caddy to tell orignal app (like plausible) what was the original ip - because otherwise they would just see `127.0.0.1` 

i'm not sure if rev-proxies will override this/add theirs anyway, so i think this mayy be left as-is (i mean the code, may still specify this as `127...`)

> So when user agent includes as much details as possible it might be more accurate.

i thought about generating random uuid at first launch and sending that - would be nice if your library allowed setting such id :+1:

Already asked them about this: 
https://github.com/plausible/analytics/discussions/1141#discussioncomment-4869310

**Comment by bostrot** [comment]
I will do some tests later, but I think the reason I used the loopback address was that Plausible wouldn't accept calls without this header, and I did not want to check the device's IP first. 

I mean you could do that anyways, even compliant if you ask your users first (not legal advice :) )

**Comment by TheLastGimbus** [comment]
Okay, that makes sense!

Anyway, would be nice to customize user-agent :eyes:

**Comment by bostrot** [comment]
> Okay, that makes sense!
> 
> Anyway, would be nice to customize user-agent :eyes:

You can customize the user agent all you want (https://github.com/bostrot/flutter_plausible_analytics/blob/1d8a0d88caf0c87f7db74cc8de55a8e79c1d9cb3/lib/plausible_analytics.dart#L16). Just make sure that you use the right format.

**Comment by TheLastGimbus** [comment]
Oh, right :sweat_smile: sorry for bother then 

big thanks for this package!

last thing - could you add some example in the readme on how to track pages visited by user?

**Comment by bostrot** [comment]
You mean something like this?

```dart
// User agent for e.g. Samsung S22
final userAgent = "Mozilla/5.0 (Linux; Android 12; SM-S906N Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/80.0.3987.119 Mobile Safari/537.36"; 

final plausible = Plausible(serverUrl, domain, userAgent: userAgent);
plausible.event(
        name: 'conversion',
        page: 'homescreen',
        referrer: 'settingscreen',
        props: {
                'app_version': 'v1.0.0',
                'app_platform': 'windows',
                'app_locale': 'de-DE',
                'app_theme': 'darkmode',
});
```

What I would do is to change the useragent string according to your device: e.g. replace Android 12 with the version and SM-S906N ... with the phone and so on.

**Comment by TheLastGimbus** [comment]
this, but binded directly to Flutter's page navigator :pray:

**Comment by bostrot** [comment]
> this, but binded directly to Flutter's page navigator 🙏

done
