### ISSUE TITLE
Flutter's page navigator support

### ISSUE THREAD

**Issue by bostrot** [bostrot/flutter_plausible_analytics#6]
this, but binded directly to Flutter's page navigator :pray:

_Originally posted by @TheLastGimbus in https://github.com/bostrot/flutter_plausible_analytics/issues/4#issuecomment-1417811921_

**Comment by bostrot** [comment]
Closed with https://github.com/bostrot/flutter_plausible_analytics/commit/52383f0ba07cf7f734015bfcd93a0d0a2fdca5b8

**Comment by TheLastGimbus** [comment]
:pray: big thanks!!
