### ISSUE TITLE
Country data not showing up

### ISSUE THREAD

**Issue by afijal** [bostrot/flutter_plausible_analytics#7]
**Describe the bug**
Country data always says no data, did anyone manage to make it work?

<img width="558" alt="Screenshot 2023-06-14 at 09 57 32" src="https://github.com/bostrot/flutter_plausible_analytics/assets/2682379/5f1d8c56-2df6-40f5-b7b0-188ff01dbb83">

Here is how I create an event
```
return event(
      name: eventName,
      page: eventPage,
      referrer: 'referrerPage',
      props: {
        'app_version': packageInfo.version,
        'app_platform': Platform.operatingSystem,
        'app_locale': Platform.localeName,
        'app_theme': MediaQuery.of(context).platformBrightness.toString(),
      },
    );```

**Comment by bostrot** [comment]
You have to set up geolocation in plausible (see plausible docs). They are not set up by default + you need to download the geodata database thing. 
Have you done this?

**Comment by afijal** [comment]
I must have missed that, thanks!

**Comment by afijal** [comment]
@bostrot I am not using a self-hosted though, can it be enabled on plausible-hosted analytics?

**Comment by bostrot** [comment]
@afijal I don't know about that. You better contact plausible about this.

**Comment by afijal** [comment]
Thanks, I will report back

**Comment by afijal** [comment]
Plausible devs helped me to identify the issue  🙏🏻
https://github.com/bostrot/flutter_plausible_analytics/pull/8
